FROM mcr.microsoft.com/dotnet/core/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["EngineSimulatorModule/EngineSimulatorModule.csproj", "EngineSimulatorModule/"]
COPY ["EngineEventGenerator/EngineEventGenerator.csproj", "EngineEventGenerator/"]
RUN dotnet restore "EngineSimulatorModule/EngineSimulatorModule.csproj"
COPY . .
WORKDIR "/src/EngineSimulatorModule"
RUN dotnet build "EngineSimulatorModule.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EngineSimulatorModule.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EngineSimulatorModule.dll"]