let min_t = ago(5h); //toscalar(telemetry | summarize min(eventtime)); 
let max_t = now();   //toscalar(telemetry | summarize max(eventtime));
telemetry
| where engineid == 'engine006'
| make-series reads=avg(temp_hpc_outlet) on eventtime in range(min_t, max_t, 10m) by engineid
| extend y_forcasted = series_decompose_forecast(reads, 7) // forecast 7 hours forward
| render timechart with(title='Expected values next 7 hours')